title: Jingzhi Shang's Homepage
page-top-title: Jingzhi Shang
top-section-bg-text: Changzhou University
top-section-bg-group-members-text: Group Members
top-section-bg-publications-text: Publications
home-subtitle: Jingzhi Shang&ensp;|&ensp;尚景智
copyright-text: '&copy; Jingzhi Shang 2025-2026. All Rights Reserved.'
